INSERT INTO brands (name, slug, active, sort_order) VALUES ('& Other Stories', 'and-other-stories', true, 10);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('4F', '4f', true, 20);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Abercrombie & Fitch', 'abercrombie-and-fitch', true, 30);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Adidas', 'adidas', true, 40);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Agent Provocateur', 'agent-provocateur', true, 50);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Aldo', 'aldo', true, 60);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Alexander McQueen', 'alexander-mcqueen', true, 70);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('American Eagle', 'american-eagle', true, 80);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Armani', 'armani', true, 90);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Asics', 'asics', true, 100);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('ASOS', 'asos', true, 110);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Atlantic', 'atlantic', true, 120);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Badura', 'badura', true, 130);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Balenciaga', 'balenciaga', true, 140);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Bape', 'bape', true, 150);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Bershka', 'bershka', true, 160);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Big Star', 'big-star', true, 170);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Birkenstock', 'birkenstock', true, 180);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Boohoo', 'boohoo', true, 190);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Bottega Veneta', 'bottega-veneta', true, 200);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Burberry', 'burberry', true, 210);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Bytom', 'bytom', true, 220);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('C&A', 'c-and-a', true, 230);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Calvin Klein', 'calvin-klein', true, 240);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Calzedonia', 'calzedonia', true, 250);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Carhartt', 'carhartt', true, 260);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('CCC', 'ccc', true, 270);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Champion', 'champion', true, 280);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Chanel', 'chanel', true, 290);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Clarks', 'clarks', true, 300);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Coccinelle', 'coccinelle', true, 310);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Columbia', 'columbia', true, 320);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Converse', 'converse', true, 330);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('COS', 'cos', true, 340);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Crocs', 'crocs', true, 350);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Cropp', 'cropp', true, 360);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Cross Jeans', 'cross-jeans', true, 370);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Deichmann', 'deichmann', true, 380);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Desigual', 'desigual', true, 390);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Dickies', 'dickies', true, 400);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Diesel', 'diesel', true, 410);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Dior', 'dior', true, 420);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Diverse', 'diverse', true, 430);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Dolce & Gabbana', 'dolce-gabbana', true, 440);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Dr. Martens', 'dr-martens', true, 450);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Ecco', 'ecco', true, 460);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Emu Australia', 'emu-australia', true, 470);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Etam', 'etam', true, 480);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Fendi', 'fendi', true, 490);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Fila', 'fila', true, 500);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Forever 21', 'forever-21', true, 510);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Furla', 'furla', true, 520);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('G-Star RAW', 'g-star-raw', true, 530);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('GAP', 'gap', true, 540);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Geox', 'geox', true, 550);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Gino Rossi', 'gino-rossi', true, 560);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Givenchy', 'givenchy', true, 570);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Gucci', 'gucci', true, 580);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Guess', 'guess', true, 590);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Gymshark', 'gymshark', true, 600);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('H&M', 'h-and-m', true, 610);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Havaianas', 'havaianas', true, 620);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Henderson', 'henderson', true, 630);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Hollister', 'hollister', true, 640);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('House', 'house', true, 650);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Hugo Boss', 'hugo-boss', true, 660);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Intimissimi', 'intimissimi', true, 670);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Jack Wolfskin', 'jack-wolfskin', true, 680);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Kappa', 'kappa', true, 690);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Karl Lagerfeld', 'karl-lagerfeld', true, 700);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Kazar', 'kazar', true, 710);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Kenzo', 'kenzo', true, 720);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Lacoste', 'lacoste', true, 730);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Lancerto', 'lancerto', true, 740);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Lasocki', 'lasocki', true, 750);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Lee', 'lee', true, 760);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Levi''s', 'levis', true, 770);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Louis Vuitton', 'louis-vuitton', true, 780);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Lululemon', 'lululemon', true, 790);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Mango', 'mango', true, 800);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Marc Jacobs', 'marc-jacobs', true, 810);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Marks & Spencer', 'marks-and-spencer', true, 820);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Massimo Dutti', 'massimo-dutti', true, 830);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Medicine', 'medicine', true, 840);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Michael Kors', 'michael-kors', true, 850);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Missguided', 'missguided', true, 860);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Mohito', 'mohito', true, 870);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Monki', 'monki', true, 880);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Monnari', 'monnari', true, 890);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Moschino', 'moschino', true, 900);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Mustang', 'mustang', true, 910);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('New Balance', 'new-balance', true, 920);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('New Look', 'new-look', true, 930);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Next', 'next', true, 940);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Nike', 'nike', true, 950);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Ochnik', 'ochnik', true, 960);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Off-White', 'off-white', true, 970);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Outhorn', 'outhorn', true, 980);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Oysho', 'oysho', true, 990);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Palace', 'palace', true, 1000);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Patagonia', 'patagonia', true, 1010);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Pepe Jeans', 'pepe-jeans', true, 1020);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Pinko', 'pinko', true, 1030);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Prada', 'prada', true, 1040);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Primark', 'primark', true, 1050);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Prosto', 'prosto', true, 1060);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Puccini', 'puccini', true, 1070);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Pull&Bear', 'pull-and-bear', true, 1080);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Quiosque', 'quiosque', true, 1090);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Ralph Lauren', 'ralph-lauren', true, 1100);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Reebok', 'reebok', true, 1110);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Reserved', 'reserved', true, 1120);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('River Island', 'river-island', true, 1130);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Ryłko', 'rylko', true, 1140);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Salomon', 'salomon', true, 1150);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Scotch & Soda', 'scotch-and-soda', true, 1160);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Shein', 'shein', true, 1170);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Sinsay', 'sinsay', true, 1180);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Steve Madden', 'steve-madden', true, 1190);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Stradivarius', 'stradivarius', true, 1200);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Stussy', 'stussy', true, 1210);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Superdry', 'superdry', true, 1220);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Supreme', 'supreme', true, 1230);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Tamaris', 'tamaris', true, 1240);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Tatuum', 'tatuum', true, 1250);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Tezenis', 'tezenis', true, 1260);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('The North Face', 'the-north-face', true, 1270);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Thrasher', 'thrasher', true, 1280);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Timberland', 'timberland', true, 1290);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Tommy Hilfiger', 'tommy-hilfiger', true, 1300);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Topshop', 'topshop', true, 1310);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Triumph', 'triumph', true, 1320);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('UGG', 'ugg', true, 1330);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Umbro', 'umbro', true, 1340);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Under Armour', 'under-armour', true, 1350);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Uniqlo', 'uniqlo', true, 1360);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Vagabond', 'vagabond', true, 1370);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Valentino', 'valentino', true, 1380);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Vans', 'vans', true, 1390);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Versace', 'versace', true, 1400);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Victoria''s Secret', 'victorias-secret', true, 1410);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Vistula', 'vistula', true, 1420);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Weekday', 'weekday', true, 1430);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Wittchen', 'wittchen', true, 1440);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Wojas', 'wojas', true, 1450);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Wólczanka', 'wolczanka', true, 1460);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Wrangler', 'wrangler', true, 1470);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Yves Saint Laurent', 'yves-saint-laurent', true, 1480);
INSERT INTO brands (name, slug, active, sort_order) VALUES ('Zara', 'zara', true, 1490);

INSERT INTO brands (name, slug, active, sort_order) VALUES ('Inna marka', 'other', true, 9999);