export const COUNTRIES = [
  { name: 'Polska', code: '+48', isoCode: 'PL', flag: '🇵🇱' },
  { name: 'Andora', code: '+376', isoCode: 'AD', flag: '🇦🇩' },
  { name: 'Zjednoczone Emiraty Arabskie', code: '+971', isoCode: 'AE', flag: '🇦🇪' },
  { name: 'Afganistan', code: '+93', isoCode: 'AF', flag: '🇦🇫' },
  { name: 'Albania', code: '+355', isoCode: 'AL', flag: '🇦🇱' },
  { name: 'Armenia', code: '+374', isoCode: 'AM', flag: '🇦🇲' },
  { name: 'Angola', code: '+244', isoCode: 'AO', flag: '🇦🇴' },
  { name: 'Argentyna', code: '+54', isoCode: 'AR', flag: '🇦🇷' },
  { name: 'Austria', code: '+43', isoCode: 'AT', flag: '🇦🇹' },
  { name: 'Australia', code: '+61', isoCode: 'AU', flag: '🇦🇺' },
  { name: 'Azerbejdżan', code: '+994', isoCode: 'AZ', flag: '🇦🇿' },
  { name: 'Bośnia i Hercegowina', code: '+387', isoCode: 'BA', flag: '🇧🇦' },
  { name: 'Belgia', code: '+32', isoCode: 'BE', flag: '🇧🇪' },
  { name: 'Bułgaria', code: '+359', isoCode: 'BG', flag: '🇧🇬' },
  { name: 'Boliwia', code: '+591', isoCode: 'BO', flag: '🇧🇴' },
  { name: 'Brazylia', code: '+55', isoCode: 'BR', flag: '🇧🇷' },
  { name: 'Białoruś', code: '+375', isoCode: 'BY', flag: '🇧🇾' },
  { name: 'Kanada', code: '+1', isoCode: 'CA', flag: '🇨🇦' },
  { name: 'Szwajcaria', code: '+41', isoCode: 'CH', flag: '🇨🇭' },
  { name: 'Chile', code: '+56', isoCode: 'CL', flag: '🇨🇱' },
  { name: 'Chiny', code: '+86', isoCode: 'CN', flag: '🇨🇳' },
  { name: 'Kolumbia', code: '+57', isoCode: 'CO', flag: '🇨🇴' },
  { name: 'Cypr', code: '+357', isoCode: 'CY', flag: '🇨🇾' },
  { name: 'Czechy', code: '+420', isoCode: 'CZ', flag: '🇨🇿' },
  { name: 'Niemcy', code: '+49', isoCode: 'DE', flag: '🇩🇪' },
  { name: 'Dania', code: '+45', isoCode: 'DK', flag: '🇩🇰' },
  { name: 'Algieria', code: '+213', isoCode: 'DZ', flag: '🇩🇿' },
  { name: 'Ekwador', code: '+593', isoCode: 'EC', flag: '🇪🇨' },
  { name: 'Estonia', code: '+372', isoCode: 'EE', flag: '🇪🇪' },
  { name: 'Egipt', code: '+20', isoCode: 'EG', flag: '🇪🇬' },
  { name: 'Hiszpania', code: '+34', isoCode: 'ES', flag: '🇪🇸' },
  { name: 'Etiopia', code: '+251', isoCode: 'ET', flag: '🇪🇹' },
  { name: 'Finlandia', code: '+358', isoCode: 'FI', flag: '🇫🇮' },
  { name: 'Francja', code: '+33', isoCode: 'FR', flag: '🇫🇷' },
  { name: 'Wielka Brytania', code: '+44', isoCode: 'GB', flag: '🇬🇧' },
  { name: 'Gruzja', code: '+995', isoCode: 'GE', flag: '🇬🇪' },
  { name: 'Ghana', code: '+233', isoCode: 'GH', flag: '🇬🇭' },
  { name: 'Grecja', code: '+30', isoCode: 'GR', flag: '🇬🇷' },
  { name: 'Chorwacja', code: '+385', isoCode: 'HR', flag: '🇭🇷' },
  { name: 'Węgry', code: '+36', isoCode: 'HU', flag: '🇭🇺' },
  { name: 'Indonezja', code: '+62', isoCode: 'ID', flag: '🇮🇩' },
  { name: 'Irlandia', code: '+353', isoCode: 'IE', flag: '🇮🇪' },
  { name: 'Izrael', code: '+972', isoCode: 'IL', flag: '🇮🇱' },
  { name: 'Indie', code: '+91', isoCode: 'IN', flag: '🇮🇳' },
  { name: 'Islandia', code: '+354', isoCode: 'IS', flag: '🇮🇸' },
  { name: 'Włochy', code: '+39', isoCode: 'IT', flag: '🇮🇹' },
  { name: 'Jordania', code: '+962', isoCode: 'JO', flag: '🇯🇴' },
  { name: 'Japonia', code: '+81', isoCode: 'JP', flag: '🇯🇵' },
  { name: 'Kenia', code: '+254', isoCode: 'KE', flag: '🇰🇪' },
  { name: 'Korea Południowa', code: '+82', isoCode: 'KR', flag: '🇰🇷' },
  { name: 'Kazachstan', code: '+7', isoCode: 'KZ', flag: '🇰🇿' },
  { name: 'Liechtenstein', code: '+423', isoCode: 'LI', flag: '🇱🇮' },
  { name: 'Litwa', code: '+370', isoCode: 'LT', flag: '🇱🇹' },
  { name: 'Luksemburg', code: '+352', isoCode: 'LU', flag: '🇱🇺' },
  { name: 'Łotwa', code: '+371', isoCode: 'LV', flag: '🇱🇻' },
  { name: 'Maroko', code: '+212', isoCode: 'MA', flag: '🇲🇦' },
  { name: 'Monako', code: '+377', isoCode: 'MC', flag: '🇲🇨' },
  { name: 'Mołdawia', code: '+373', isoCode: 'MD', flag: '🇲🇩' },
  { name: 'Czarnogóra', code: '+382', isoCode: 'ME', flag: '🇲🇪' },
  { name: 'Macedonia Północna', code: '+389', isoCode: 'MK', flag: '🇲🇰' },
  { name: 'Malta', code: '+356', isoCode: 'MT', flag: '🇲🇹' },
  { name: 'Meksyk', code: '+52', isoCode: 'MX', flag: '🇲🇽' },
  { name: 'Nigeria', code: '+234', isoCode: 'NG', flag: '🇳🇬' },
  { name: 'Holandia', code: '+31', isoCode: 'NL', flag: '🇳🇱' },
  { name: 'Norwegia', code: '+47', isoCode: 'NO', flag: '🇳🇴' },
  { name: 'Nowa Zelandia', code: '+64', isoCode: 'NZ', flag: '🇳🇿' },
  { name: 'Pakistan', code: '+92', isoCode: 'PK', flag: '🇵🇰' },
  { name: 'Filipiny', code: '+63', isoCode: 'PH', flag: '🇵🇭' },
  { name: 'Portugalia', code: '+351', isoCode: 'PT', flag: '🇵🇹' },
  { name: 'Paragwaj', code: '+595', isoCode: 'PY', flag: '🇵🇾' },
  { name: 'Katar', code: '+974', isoCode: 'QA', flag: '🇶🇦' },
  { name: 'Rumunia', code: '+40', isoCode: 'RO', flag: '🇷🇴' },
  { name: 'Serbia', code: '+381', isoCode: 'RS', flag: '🇷🇸' },
  { name: 'Szwecja', code: '+46', isoCode: 'SE', flag: '🇸🇪' },
  { name: 'Słowenia', code: '+386', isoCode: 'SI', flag: '🇸🇮' },
  { name: 'Słowacja', code: '+421', isoCode: 'SK', flag: '🇸🇰' },
  { name: 'San Marino', code: '+378', isoCode: 'SM', flag: '🇸🇲' },
  { name: 'Senegal', code: '+221', isoCode: 'SN', flag: '🇸🇳' },
  { name: 'Tajlandia', code: '+66', isoCode: 'TH', flag: '🇹🇭' },
  { name: 'Tunezja', code: '+216', isoCode: 'TN', flag: '🇹🇳' },
  { name: 'Turcja', code: '+90', isoCode: 'TR', flag: '🇹🇷' },
  { name: 'Ukraina', code: '+380', isoCode: 'UA', flag: '🇺🇦' },
  { name: 'USA', code: '+1', isoCode: 'US', flag: '🇺🇸' },
  { name: 'Urugwaj', code: '+598', isoCode: 'UY', flag: '🇺🇾' },
  { name: 'Watykan', code: '+39', isoCode: 'VA', flag: '🇻🇦' },
  { name: 'Wietnam', code: '+84', isoCode: 'VN', flag: '🇻🇳' },
  { name: 'RPA', code: '+27', isoCode: 'ZA', flag: '🇿🇦' }
];
